name: Workflow from scratch

on:
  push:
    branches:
      - main
      - 'feature/*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package
#  publish-docker:
#    runs-on: ubuntu-latest
#    needs: build
