name: Workflow from scratch

on:
  push:
    branches:
      - main
      - 'feature/*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

  publish-docker:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub
        run: docker login gchr.io -u mugibor -p ${{ github.token }}

      - name: Build the Docker Image
        run: docker build . -t ghcr.io/mugibor/cubix-cloudnative-block1-homework/app:springboot
